name: Render & Release Manim

on:
  push:
    tags:
      - "v*"

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.Auth }}

      - name: Make an authenticated API request
        run: |
          curl --request GET \
          --url "api.github.com" \
          --header "Authorization: Bearer ${{ secrets.Auth }}"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ffmpeg \
            libcairo2-dev \
            texlive \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            python3-pip \
            libpango1.0-dev \
            libpangocairo-1.0-0 \
            zsh
          pip install manim

      - name: Make script executable
        run: chmod +x ./RUN

      - name: Render scene
        run: ./RUN
        shell: zsh {0}

      - name: Create GitHub Release for Tag
        uses: ghactions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Release for ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.Auth }}

      - name: Upload video to release
        uses: softprops/action-gh-release@v2
        with:
          files: S.mp4
          GITHUB_TOKEN: ${{ secrets.Auth }}
